[tool.poetry]
name = "gittest"
version = "0.1.0"
description = ""
authors = ["Nikolay Stepanov <happystydio@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
prettytable = "^3.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
